// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/power_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/power_service.go -destination=internal/service/mock_reading_querier.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/ahovingtonpower-dashboard/internal/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReadingQuerier is a mock of ReadingQuerier interface.
type MockReadingQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockReadingQuerierMockRecorder
}

// MockReadingQuerierMockRecorder is the mock recorder for MockReadingQuerier.
type MockReadingQuerierMockRecorder struct {
	mock *MockReadingQuerier
}

// NewMockReadingQuerier creates a new mock instance.
func NewMockReadingQuerier(ctrl *gomock.Controller) *MockReadingQuerier {
	mock := &MockReadingQuerier{ctrl: ctrl}
	mock.recorder = &MockReadingQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadingQuerier) EXPECT() *MockReadingQuerierMockRecorder {
	return m.recorder
}

// GetLatestBatteryStatus mocks base method.
func (m *MockReadingQuerier) GetLatestBatteryStatus(ctx context.Context, deviceID uuid.UUID) (*model.BatteryStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBatteryStatus", ctx, deviceID)
	ret0, _ := ret[0].(*model.BatteryStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBatteryStatus indicates an expected call of GetLatestBatteryStatus.
func (mr *MockReadingQuerierMockRecorder) GetLatestBatteryStatus(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBatteryStatus", reflect.TypeOf((*MockReadingQuerier)(nil).GetLatestBatteryStatus), ctx, deviceID)
}

// GetAggregatedReadings mocks base method.
func (m *MockReadingQuerier) GetAggregatedReadings(ctx context.Context, deviceID uuid.UUID, interval string, start, end time.Time) ([]*model.PowerReading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedReadings", ctx, deviceID, interval, start, end)
	ret0, _ := ret[0].([]*model.PowerReading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedReadings indicates an expected call of GetAggregatedReadings.
func (mr *MockReadingQuerierMockRecorder) GetAggregatedReadings(ctx, deviceID, interval, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedReadings", reflect.TypeOf((*MockReadingQuerier)(nil).GetAggregatedReadings), ctx, deviceID, interval, start, end)
}

// GetLatestReadings mocks base method.
func (m *MockReadingQuerier) GetLatestReadings(ctx context.Context, deviceID uuid.UUID, limit int) ([]*model.PowerReading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestReadings", ctx, deviceID, limit)
	ret0, _ := ret[0].([]*model.PowerReading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestReadings indicates an expected call of GetLatestReadings.
func (mr *MockReadingQuerierMockRecorder) GetLatestReadings(ctx, deviceID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestReadings", reflect.TypeOf((*MockReadingQuerier)(nil).GetLatestReadings), ctx, deviceID, limit)
}
