// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ahovingtonpower-dashboard/internal/api (interfaces: PowerServicer)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mock_power_servicer.go -package=service -mock_names PowerServicer=MockPowerServicer github.com/ahovingtonpower-dashboard/internal/api PowerServicer
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/ahovingtonpower-dashboard/internal/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPowerServicer is a mock of PowerServicer interface.
type MockPowerServicer struct {
	ctrl     *gomock.Controller
	recorder *MockPowerServicerMockRecorder
}

// MockPowerServicerMockRecorder is the mock recorder for MockPowerServicer.
type MockPowerServicerMockRecorder struct {
	mock *MockPowerServicer
}

// NewMockPowerServicer creates a new mock instance.
func NewMockPowerServicer(ctrl *gomock.Controller) *MockPowerServicer {
	mock := &MockPowerServicer{ctrl: ctrl}
	mock.recorder = &MockPowerServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPowerServicer) EXPECT() *MockPowerServicerMockRecorder {
	return m.recorder
}

// GetCurrentStatus mocks base method.
func (m *MockPowerServicer) GetCurrentStatus(arg0 context.Context, arg1 uuid.UUID) (*model.PowerReading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentStatus", arg0, arg1)
	ret0, _ := ret[0].(*model.PowerReading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentStatus indicates an expected call of GetCurrentStatus.
func (mr *MockPowerServicerMockRecorder) GetCurrentStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentStatus", reflect.TypeOf((*MockPowerServicer)(nil).GetCurrentStatus), arg0, arg1)
}

// GetHistory mocks base method.
func (m *MockPowerServicer) GetHistory(arg0 context.Context, arg1 uuid.UUID, arg2 string, arg3, arg4 time.Time) ([]*model.PowerReading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*model.PowerReading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockPowerServicerMockRecorder) GetHistory(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockPowerServicer)(nil).GetHistory), arg0, arg1, arg2, arg3, arg4)
}
