// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/adapter/provider_adapter.go
//
// Generated by this command:
//
//	mockgen -source=pkg/adapter/provider_adapter.go -destination=pkg/adapter/mock_provider_adapter.go -package=adapter
//

// Package adapter is a generated GoMock package.
package adapter

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockProviderAdapter is a mock of ProviderAdapter interface.
type MockProviderAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockProviderAdapterMockRecorder
}

// MockProviderAdapterMockRecorder is the mock recorder for MockProviderAdapter.
type MockProviderAdapterMockRecorder struct {
	mock *MockProviderAdapter
}

// NewMockProviderAdapter creates a new mock instance.
func NewMockProviderAdapter(ctrl *gomock.Controller) *MockProviderAdapter {
	mock := &MockProviderAdapter{ctrl: ctrl}
	mock.recorder = &MockProviderAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderAdapter) EXPECT() *MockProviderAdapterMockRecorder {
	return m.recorder
}

// GetBatteryStatus mocks base method.
func (m *MockProviderAdapter) GetBatteryStatus(ctx context.Context) (*BatteryStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatteryStatus", ctx)
	ret0, _ := ret[0].(*BatteryStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatteryStatus indicates an expected call of GetBatteryStatus.
func (mr *MockProviderAdapterMockRecorder) GetBatteryStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatteryStatus", reflect.TypeOf((*MockProviderAdapter)(nil).GetBatteryStatus), ctx)
}

// GetDeviceList mocks base method.
func (m *MockProviderAdapter) GetDeviceList(ctx context.Context) ([]DeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceList", ctx)
	ret0, _ := ret[0].([]DeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceList indicates an expected call of GetDeviceList.
func (mr *MockProviderAdapterMockRecorder) GetDeviceList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceList", reflect.TypeOf((*MockProviderAdapter)(nil).GetDeviceList), ctx)
}

// GetPowerMetrics mocks base method.
func (m *MockProviderAdapter) GetPowerMetrics(ctx context.Context, duration time.Duration) ([]PowerMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPowerMetrics", ctx, duration)
	ret0, _ := ret[0].([]PowerMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPowerMetrics indicates an expected call of GetPowerMetrics.
func (mr *MockProviderAdapterMockRecorder) GetPowerMetrics(ctx, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPowerMetrics", reflect.TypeOf((*MockProviderAdapter)(nil).GetPowerMetrics), ctx, duration)
}

// GetPowerQuality mocks base method.
func (m *MockProviderAdapter) GetPowerQuality(ctx context.Context) (*PowerQualityMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPowerQuality", ctx)
	ret0, _ := ret[0].(*PowerQualityMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPowerQuality indicates an expected call of GetPowerQuality.
func (mr *MockProviderAdapterMockRecorder) GetPowerQuality(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPowerQuality", reflect.TypeOf((*MockProviderAdapter)(nil).GetPowerQuality), ctx)
}

// GetSystemStatus mocks base method.
func (m *MockProviderAdapter) GetSystemStatus(ctx context.Context) (*SystemStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemStatus", ctx)
	ret0, _ := ret[0].(*SystemStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemStatus indicates an expected call of GetSystemStatus.
func (mr *MockProviderAdapterMockRecorder) GetSystemStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemStatus", reflect.TypeOf((*MockProviderAdapter)(nil).GetSystemStatus), ctx)
}
